### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by dizcology**

### CODE REVIEW

**Comment by bcoe** [comment]
@dizcology this is auto-generated nightly, you can create a [.readme-partials.json](https://github.com/googleapis/nodejs-storage/blob/master/.readme-partials.yaml) to provide a more detailed description 👍 

I linked a file for reference.

**Review by sofisl — APPROVED** [review]

**Comment by bcoe** [comment]
@dizcology the README is managed by a template, you can instead add a partial to the repository that looks something like this:

https://github.com/googleapis/nodejs-storage/blob/master/.readme-partials.yaml

**Review by bcoe — CHANGES_REQUESTED** [review]
The README will be reverted on the nightly template run.

**Comment by sofisl** [comment]
@dizcology, friendly bump on this PR!

**Pull request closed without merging**
